### PR TITLE
Use io.StringWriter

### PR DESCRIPTION
**Pull request by yongchongye**
Benchmarks against the previous implementation
[new-iowriter.txt](https://github.com/choonkeat/dom-go/files/13308575/new-iowriter.txt)
[new-stringwriter.txt](https://github.com/choonkeat/dom-go/files/13308577/new-stringwriter.txt)
[old.txt](https://github.com/choonkeat/dom-go/files/13308579/old.txt)

```
benchstat old=old.txt new=new-stringwriter.txt  
goos: darwin
goarch: arm64
pkg: github.com/choonkeat/dom-go
               │     old     │                 new                 │
               │   sec/op    │   sec/op     vs base                │
AttrHTML-8       123.9n ± 2%   157.5n ± 1%  +27.12% (p=0.000 n=10)
NodeHTML-8       520.4n ± 0%   670.9n ± 2%  +28.91% (p=0.000 n=10)
HtmlTemplate-8   3.312µ ± 1%   3.378µ ± 1%   +1.98% (p=0.001 n=10)
geomean          597.8n        709.3n       +18.67%

           │     old     │                 new                 │
           │  AttrHTML   │  AttrHTML    vs base                │
AttrHTML-8   9.479M ± 4%   7.499M ± 7%  -20.89% (p=0.000 n=10)

               │     old      │                  new                   │
               │     B/op     │     B/op      vs base                  │
AttrHTML-8         128.0 ± 0%     160.0 ± 0%  +25.00% (p=0.000 n=10)
NodeHTML-8         456.0 ± 0%     800.0 ± 0%  +75.44% (p=0.000 n=10)
HtmlTemplate-8   1.352Ki ± 0%   1.352Ki ± 0%        ~ (p=1.000 n=10) ¹
geomean            432.3          561.6       +29.92%
¹ all samples are equal

               │    old     │                 new                  │
               │ allocs/op  │ allocs/op   vs base                  │
AttrHTML-8       4.000 ± 0%   5.000 ± 0%  +25.00% (p=0.000 n=10)
NodeHTML-8       11.00 ± 0%   16.00 ± 0%  +45.45% (p=0.000 n=10)
HtmlTemplate-8   53.00 ± 0%   53.00 ± 0%        ~ (p=1.000 n=10) ¹
geomean          13.26        16.19       +22.05%
¹ all samples are equal

           │     old     │                 new                 │
           │  NodeHTML   │  NodeHTML    vs base                │
NodeHTML-8   2.297M ± 1%   1.797M ± 3%  -21.77% (p=0.000 n=10)

               │     old      │              new               │
               │ HTMLTemplate │ HTMLTemplate  vs base          │
HtmlTemplate-8    354.2k ± 0%    351.9k ± 2%  ~ (p=0.631 n=10)
```

### CODE REVIEW

**Comment by choonkeat** [comment]
the numbers don't look good, huh :-(

my understanding is that the goal is to get `func (e Node) Write(w io.StringWriter)` where we can supply our own `io.StringWriter`

how about we instead expose our internal helper

```diff
-func (a Attribute) buildHTML(sb *strings.Builder) *strings.Builder {
+func (a Attribute) HTMLBuilder(sb *strings.Builder) *strings.Builder {
```

so instead of _only_ being able to call `HTML()`, now we have another function we can call to provide our `strings.Builder`

**Comment by choonkeat** [comment]
however with

- BenchmarkNodeHTMLBuildMany : doing `HTMLBuilder(&sb); HTMLBuilder(&sb); HTMLBuilder(&sb)`; didn't even call `sb.String()`
- BenchmarkNodeHTMLMany: doing `HTML() + HTML() + HTML()`

`HTMLBuilder(sb *strings.Builder) *strings.Builder` doesn't look like it outperforms by much

```
BenchmarkAttrHTML-8            	 9900267	       121.1 ns/op	   9900267 AttrHTML	     128 B/op	       4 allocs/op
BenchmarkNodeHTML-8            	 2326978	       514.4 ns/op	   2326978 NodeHTML	     456 B/op	      11 allocs/op
BenchmarkNodeHTMLBuildMany-8   	  790669	      1490 ns/op	    790669 NodeHTML	    1640 B/op	      25 allocs/op
BenchmarkNodeHTMLMany-8        	  744154	      1591 ns/op	    744154 NodeHTML	    1656 B/op	      34 allocs/op
BenchmarkHtmlTemplate-8        	  357118	      3330 ns/op	    357118 HTMLTemplate	    1384 B/op	      53 allocs/op
```

**Comment by yongchongye** [comment]
then I close this PR? maybe relook at it if we hit any performance issues during load tests?

**Comment by choonkeat** [comment]
👌

**Pull request closed without merging**
